# Generated by Django 4.1.2 on 2022-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_delete_videoproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
