# Generated by Django 4.1.2 on 2022-11-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publishtimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
